# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anamenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(1017, 533)
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/pngegg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setStyleSheet("background-color: rgb(70, 70, 70);")
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonYenile = QtWidgets.QPushButton(Dialog)
        self.pushButtonYenile.setStyleSheet("background-color: rgb(255, 237, 224);\n"
"background-color: rgb(214, 214, 214);\n"
"font: 10pt \"Arial\";\n"
"border-radius:7px;")
        self.pushButtonYenile.setObjectName("pushButtonYenile")
        self.horizontalLayout.addWidget(self.pushButtonYenile)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.tableWidgetListe = QtWidgets.QTableWidget(Dialog)
        self.tableWidgetListe.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tableWidgetListe.setObjectName("tableWidgetListe")
        self.tableWidgetListe.setColumnCount(10)
        self.tableWidgetListe.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListe.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListe.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListe.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListe.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListe.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListe.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListe.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListe.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListe.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetListe.setHorizontalHeaderItem(9, item)
        self.verticalLayout.addWidget(self.tableWidgetListe)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonEkle = QtWidgets.QPushButton(Dialog)
        self.pushButtonEkle.setStyleSheet("background-color: rgb(255, 237, 224);\n"
"background-color: rgb(214, 214, 214);\n"
"font: 10pt \"Arial\";\n"
"border-radius:7px;")
        self.pushButtonEkle.setObjectName("pushButtonEkle")
        self.horizontalLayout_2.addWidget(self.pushButtonEkle)
        self.pushButtonDuzenle = QtWidgets.QPushButton(Dialog)
        self.pushButtonDuzenle.setStyleSheet("background-color: rgb(255, 237, 224);\n"
"background-color: rgb(214, 214, 214);\n"
"font: 10pt \"Arial\";\n"
"border-radius:7px;")
        self.pushButtonDuzenle.setObjectName("pushButtonDuzenle")
        self.horizontalLayout_2.addWidget(self.pushButtonDuzenle)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 3)
        self.commandLinkButtonSSS = QtWidgets.QCommandLinkButton(Dialog)
        self.commandLinkButtonSSS.setStyleSheet("font: 75 8pt \"Verdana\";\n"
"font: 75 8pt \"Verdana\";\n"
"")
        self.commandLinkButtonSSS.setObjectName("commandLinkButtonSSS")
        self.gridLayout.addWidget(self.commandLinkButtonSSS, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setStyleSheet("color: rgb(0,0,0);\n"
"font: 30pt \"Arial\";\n"
"border-radius:5px;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.commandLinkButtonHakkimizda = QtWidgets.QCommandLinkButton(Dialog)
        self.commandLinkButtonHakkimizda.setStyleSheet("\n"
"font: 75 8pt \"Verdana\";")
        self.commandLinkButtonHakkimizda.setObjectName("commandLinkButtonHakkimizda")
        self.gridLayout.addWidget(self.commandLinkButtonHakkimizda, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "EMR OTO"))
        self.pushButtonYenile.setText(_translate("Dialog", "  YENİLE  "))
        item = self.tableWidgetListe.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.tableWidgetListe.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "ARAÇ MODELİ"))
        item = self.tableWidgetListe.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "MOTOR HACMİ"))
        item = self.tableWidgetListe.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "ARAÇ YILI"))
        item = self.tableWidgetListe.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "KM"))
        item = self.tableWidgetListe.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "YAPILAN İŞLEM"))
        item = self.tableWidgetListe.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "YAPILIŞ TARİHİ"))
        item = self.tableWidgetListe.horizontalHeaderItem(7)
        item.setText(_translate("Dialog", "SAAT"))
        item = self.tableWidgetListe.horizontalHeaderItem(8)
        item.setText(_translate("Dialog", "PLAKA"))
        item = self.tableWidgetListe.horizontalHeaderItem(9)
        item.setText(_translate("Dialog", "ŞİKAYET"))
        self.pushButtonEkle.setText(_translate("Dialog", "   EKLE   "))
        self.pushButtonDuzenle.setText(_translate("Dialog", " DÜZENLE "))
        self.commandLinkButtonSSS.setText(_translate("Dialog", "Sıkca Sorulan Sorular"))
        self.label_3.setText(_translate("Dialog", "      ANASAYFA"))
        self.commandLinkButtonHakkimizda.setText(_translate("Dialog", "HAKKIMIZDA"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
