# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'giris.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(344, 421)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/pngegg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"background-color: rgb(70, 70, 70);\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEditGirisKullaniciAdi = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditGirisKullaniciAdi.setGeometry(QtCore.QRect(80, 90, 171, 31))
        self.lineEditGirisKullaniciAdi.setStyleSheet("background-color: rgb(255, 255, 255);;\n"
"border: none;\n"
"border-radius:10px;\n"
"font: 8pt \"Arial\";\n"
"")
        self.lineEditGirisKullaniciAdi.setObjectName("lineEditGirisKullaniciAdi")
        self.lineEditGirisSifre = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditGirisSifre.setGeometry(QtCore.QRect(80, 130, 171, 31))
        self.lineEditGirisSifre.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:10px;\n"
"font: 8pt \"Arial\";")
        self.lineEditGirisSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditGirisSifre.setObjectName("lineEditGirisSifre")
        self.pushButtonGiris = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGiris.setGeometry(QtCore.QRect(70, 210, 75, 23))
        self.pushButtonGiris.setStyleSheet("background-color: rgb(255, 237, 224);\n"
"background-color: rgb(214, 214, 214);\n"
"font: 10pt \"Arial\";\n"
"border-radius:7px;")
        self.pushButtonGiris.setObjectName("pushButtonGiris")
        self.pushButtonKayitOl = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonKayitOl.setGeometry(QtCore.QRect(180, 210, 75, 23))
        self.pushButtonKayitOl.setStyleSheet("background-color: rgb(255, 237, 224);\n"
"background-color: rgb(214, 214, 214);\n"
"font: 75 10pt \"Arial\";\n"
"border-radius:7px;\n"
"\n"
"")
        self.pushButtonKayitOl.setObjectName("pushButtonKayitOl")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 20, 271, 331))
        self.label.setStyleSheet("background-color: rgb(95, 95, 95);\n"
"\n"
"border-radius:10px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 30, 171, 31))
        self.label_2.setStyleSheet("color: rgb(255,255,255);\n"
"background-color: rgb(0, 0, 0);\n"
"border-radius:7px;\n"
"font: 12pt \"Arial\";")
        self.label_2.setObjectName("label_2")
        self.label.raise_()
        self.lineEditGirisKullaniciAdi.raise_()
        self.lineEditGirisSifre.raise_()
        self.pushButtonGiris.raise_()
        self.pushButtonKayitOl.raise_()
        self.label_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 344, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GİRİŞ-EMR OTO"))
        self.lineEditGirisKullaniciAdi.setPlaceholderText(_translate("MainWindow", "Kullanıcı Adı"))
        self.lineEditGirisSifre.setPlaceholderText(_translate("MainWindow", "Şifre"))
        self.pushButtonGiris.setText(_translate("MainWindow", "GİRİŞ"))
        self.pushButtonKayitOl.setText(_translate("MainWindow", "KAYIT OL"))
        self.label_2.setText(_translate("MainWindow", "                GİRİŞ"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
