# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kayitol.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(335, 421)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/pngegg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(70, 70, 70);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 20, 271, 331))
        self.label_8.setStyleSheet("background-color: rgb(95, 95, 95);\n"
"border-radius:10px;")
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 30, 251, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setStyleSheet("\n"
"font: 75 8pt \"Verdana\";")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEditKayitAd = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditKayitAd.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.lineEditKayitAd.setObjectName("lineEditKayitAd")
        self.horizontalLayout.addWidget(self.lineEditKayitAd)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("\n"
"font: 75 8pt \"Verdana\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.lineEditKayitSoyad = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditKayitSoyad.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.lineEditKayitSoyad.setObjectName("lineEditKayitSoyad")
        self.horizontalLayout_2.addWidget(self.lineEditKayitSoyad)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setStyleSheet("\n"
"font: 75 8pt \"Verdana\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineEditKayitTelefon = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditKayitTelefon.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";\n"
"")
        self.lineEditKayitTelefon.setObjectName("lineEditKayitTelefon")
        self.horizontalLayout_3.addWidget(self.lineEditKayitTelefon)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setStyleSheet("\n"
"font: 75 8pt \"Verdana\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.lineEditKayitKullaniciAdi = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditKayitKullaniciAdi.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.lineEditKayitKullaniciAdi.setObjectName("lineEditKayitKullaniciAdi")
        self.horizontalLayout_4.addWidget(self.lineEditKayitKullaniciAdi)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("\n"
"font: 75 8pt \"Verdana\";")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.lineEditKayitSifre = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditKayitSifre.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.lineEditKayitSifre.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditKayitSifre.setObjectName("lineEditKayitSifre")
        self.horizontalLayout_5.addWidget(self.lineEditKayitSifre)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setStyleSheet("\n"
"font: 75 8pt \"Verdana\";")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.lineEditKayitSifre2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditKayitSifre2.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.lineEditKayitSifre2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEditKayitSifre2.setObjectName("lineEditKayitSifre2")
        self.horizontalLayout_6.addWidget(self.lineEditKayitSifre2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setStyleSheet("\n"
"font: 75 8pt \"Verdana\";\n"
"")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.lineEditKayiteEMail = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEditKayiteEMail.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.lineEditKayiteEMail.setInputMask("")
        self.lineEditKayiteEMail.setObjectName("lineEditKayiteEMail")
        self.horizontalLayout_7.addWidget(self.lineEditKayiteEMail)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.pushButtonKayitKayit = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButtonKayitKayit.setStyleSheet("background-color: rgb(255, 237, 224);\n"
"background-color: rgb(214, 214, 214);\n"
"font: 10pt \"Arial\";\n"
"border-radius:7px;")
        self.pushButtonKayitKayit.setObjectName("pushButtonKayitKayit")
        self.verticalLayout.addWidget(self.pushButtonKayitKayit)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 335, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kayıt Ol"))
        self.label.setText(_translate("MainWindow", "Ad:"))
        self.label_4.setText(_translate("MainWindow", "Soyad:"))
        self.label_2.setText(_translate("MainWindow", "Telefon(+90):"))
        self.lineEditKayitTelefon.setInputMask(_translate("MainWindow", "9(999) 999 9999"))
        self.lineEditKayitTelefon.setPlaceholderText(_translate("MainWindow", "_ ___ ___ __ __"))
        self.label_3.setText(_translate("MainWindow", "KullanıcıAdı:"))
        self.label_5.setText(_translate("MainWindow", "Şifre:"))
        self.label_6.setText(_translate("MainWindow", "Şifre Tekrar:"))
        self.label_7.setText(_translate("MainWindow", "E MAIL:"))
        self.pushButtonKayitKayit.setText(_translate("MainWindow", "Kayıt Ol"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
