# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ekle.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(639, 529)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/pngegg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 9, 611, 481))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEditAracModeli = QtWidgets.QLineEdit(self.widget)
        self.lineEditAracModeli.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.lineEditAracModeli.setText("")
        self.lineEditAracModeli.setObjectName("lineEditAracModeli")
        self.horizontalLayout.addWidget(self.lineEditAracModeli)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("background-color: rgb(95, 95, 95);\n"
"font: 75 8pt \"Verdana\";")
        self.label.setObjectName("label")
        self.horizontalLayout_9.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.textEditSikayet = QtWidgets.QTextEdit(self.widget)
        self.textEditSikayet.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.textEditSikayet.setObjectName("textEditSikayet")
        self.verticalLayout.addWidget(self.textEditSikayet)
        self.gridLayout.addLayout(self.verticalLayout, 0, 1, 5, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBoxMotorHacmi = QtWidgets.QComboBox(self.widget)
        self.comboBoxMotorHacmi.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.comboBoxMotorHacmi.setObjectName("comboBoxMotorHacmi")
        self.comboBoxMotorHacmi.addItem("")
        self.comboBoxMotorHacmi.addItem("")
        self.comboBoxMotorHacmi.addItem("")
        self.comboBoxMotorHacmi.addItem("")
        self.comboBoxMotorHacmi.addItem("")
        self.comboBoxMotorHacmi.addItem("")
        self.comboBoxMotorHacmi.addItem("")
        self.comboBoxMotorHacmi.addItem("")
        self.comboBoxMotorHacmi.addItem("")
        self.comboBoxMotorHacmi.addItem("")
        self.comboBoxMotorHacmi.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBoxMotorHacmi)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEditAracYili = QtWidgets.QLineEdit(self.widget)
        self.lineEditAracYili.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.lineEditAracYili.setObjectName("lineEditAracYili")
        self.horizontalLayout_3.addWidget(self.lineEditAracYili)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEditKM = QtWidgets.QLineEdit(self.widget)
        self.lineEditKM.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.lineEditKM.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEditKM.setObjectName("lineEditKM")
        self.horizontalLayout_4.addWidget(self.lineEditKM)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEditYapilanIslem = QtWidgets.QLineEdit(self.widget)
        self.lineEditYapilanIslem.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.lineEditYapilanIslem.setObjectName("lineEditYapilanIslem")
        self.horizontalLayout_5.addWidget(self.lineEditYapilanIslem)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("background-color: rgb(95, 95, 95);\n"
"font: 75 8pt \"Verdana\";")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.dateEditTarih = QtWidgets.QDateEdit(self.widget)
        self.dateEditTarih.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"\n"
"font: 8pt \"Arial\";")
        self.dateEditTarih.setObjectName("dateEditTarih")
        self.horizontalLayout_6.addWidget(self.dateEditTarih)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setStyleSheet("background-color: rgb(95, 95, 95);\n"
"font: 75 8pt \"Verdana\";")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.timeEditSaat = QtWidgets.QTimeEdit(self.widget)
        self.timeEditSaat.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"\n"
"font: 8pt \"Arial\";")
        self.timeEditSaat.setObjectName("timeEditSaat")
        self.horizontalLayout_7.addWidget(self.timeEditSaat)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_7, 6, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEditPlaka = QtWidgets.QLineEdit(self.widget)
        self.lineEditPlaka.setStyleSheet("background-color: rgb(255, 255, 255);border: none;\n"
"border-radius:7px;\n"
"font: 8pt \"Arial\";")
        self.lineEditPlaka.setObjectName("lineEditPlaka")
        self.horizontalLayout_8.addWidget(self.lineEditPlaka)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.pushButtonEkle = QtWidgets.QPushButton(self.widget)
        self.pushButtonEkle.setStyleSheet("background-color: rgb(255, 237, 224);\n"
"background-color: rgb(214, 214, 214);\n"
"font: 10pt \"Arial\";\n"
"border-radius:7px;")
        self.pushButtonEkle.setObjectName("pushButtonEkle")
        self.horizontalLayout_10.addWidget(self.pushButtonEkle)
        self.pushButtonGeriDon = QtWidgets.QPushButton(self.widget)
        self.pushButtonGeriDon.setStyleSheet("background-color: rgb(255, 237, 224);\n"
"background-color: rgb(214, 214, 214);\n"
"font: 10pt \"Arial\";\n"
"border-radius:7px;")
        self.pushButtonGeriDon.setObjectName("pushButtonGeriDon")
        self.horizontalLayout_10.addWidget(self.pushButtonGeriDon)
        self.gridLayout.addLayout(self.horizontalLayout_10, 8, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 639, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ekle"))
        self.lineEditAracModeli.setPlaceholderText(_translate("MainWindow", "Araç Modeli"))
        self.label.setText(_translate("MainWindow", "ŞİKAYETİ"))
        self.textEditSikayet.setPlaceholderText(_translate("MainWindow", "..."))
        self.comboBoxMotorHacmi.setCurrentText(_translate("MainWindow", "1.0 SCE"))
        self.comboBoxMotorHacmi.setItemText(0, _translate("MainWindow", "1.0 SCE"))
        self.comboBoxMotorHacmi.setItemText(1, _translate("MainWindow", "1.0 TCE"))
        self.comboBoxMotorHacmi.setItemText(2, _translate("MainWindow", "1.3 TCE"))
        self.comboBoxMotorHacmi.setItemText(3, _translate("MainWindow", "1.3 Hybrid"))
        self.comboBoxMotorHacmi.setItemText(4, _translate("MainWindow", "1.5 DCI"))
        self.comboBoxMotorHacmi.setItemText(5, _translate("MainWindow", "1.5 Blue DCi"))
        self.comboBoxMotorHacmi.setItemText(6, _translate("MainWindow", "1.6"))
        self.comboBoxMotorHacmi.setItemText(7, _translate("MainWindow", "1.7"))
        self.comboBoxMotorHacmi.setItemText(8, _translate("MainWindow", "1.8"))
        self.comboBoxMotorHacmi.setItemText(9, _translate("MainWindow", "1.9"))
        self.comboBoxMotorHacmi.setItemText(10, _translate("MainWindow", "2.0"))
        self.lineEditAracYili.setInputMask(_translate("MainWindow", "9999"))
        self.lineEditAracYili.setPlaceholderText(_translate("MainWindow", "ARAÇ YILI"))
        self.lineEditKM.setInputMask(_translate("MainWindow", "999999"))
        self.lineEditKM.setPlaceholderText(_translate("MainWindow", "KM"))
        self.lineEditYapilanIslem.setPlaceholderText(_translate("MainWindow", "YAPILAN İŞLEM"))
        self.label_2.setText(_translate("MainWindow", "Tarih"))
        self.label_3.setText(_translate("MainWindow", "Saat"))
        self.lineEditPlaka.setPlaceholderText(_translate("MainWindow", "PLAKA"))
        self.pushButtonEkle.setText(_translate("MainWindow", "Ekle"))
        self.pushButtonGeriDon.setText(_translate("MainWindow", "Geri Dön"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
