# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hakkimizda.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 533)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/pngegg.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEditHakkimizda = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditHakkimizda.setGeometry(QtCore.QRect(20, 20, 411, 391))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.textEditHakkimizda.setFont(font)
        self.textEditHakkimizda.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(95, 95, 95, 95);\n"
"font: 75 8pt \"Verdana\";")
        self.textEditHakkimizda.setReadOnly(True)
        self.textEditHakkimizda.setObjectName("textEditHakkimizda")
        self.pushButtonHakkimizdaGeriDon = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonHakkimizdaGeriDon.setGeometry(QtCore.QRect(310, 440, 101, 31))
        self.pushButtonHakkimizdaGeriDon.setStyleSheet("background-color: rgb(255, 237, 224);\n"
"background-color: rgb(214, 214, 214);\n"
"font: 10pt \"Arial\";\n"
"border-radius:7px;")
        self.pushButtonHakkimizdaGeriDon.setObjectName("pushButtonHakkimizdaGeriDon")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 10, 41, 81))
        self.label_2.setStyleSheet("image: url(:/reno/renoult.jpg);\n"
"background-color: rgba(95, 95, 95, 95);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 10, 41, 81))
        self.label_3.setStyleSheet("image: url(:/reno/renoult.jpg);\n"
"background-color: rgba(95, 95, 95, 95);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HAKKIMIZDA"))
        self.textEditHakkimizda.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Verdana\'; font-size:8pt; font-weight:72; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\">    </span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:600; color:#ffffff;\">Misyonumuz işletmenizin dijital dönüşümünü tamamlayıp büyümeye odaklanmanızı sağlamaktır.</span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:600; color:#ff0000;\"> </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\"><br /></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400;\">    </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:14pt; font-weight:400;\">20 yıllık otomobil servisi tecrübesi ile bilişim sektörü tecrübesini bir araya getirip servis işletmenizin yönetim sistemi ihtiyacını uçtan uca çözüm sunmak üzere yola çıktık. Siz değerli müşterilerimizle açık iletişim kanalları kurarak değişen ihtiyaçlarınızı anında analiz etme imkanı sunuyoruz. Sürekli iyileştirme felsefesiyle son teknolojinin sunduğu imkanları en uygun fiyata hizmetinize sunarak işletmenize fayda sağlıyoruz. Bizimle büyümeye devam edin!</span></p></body></html>"))
        self.pushButtonHakkimizdaGeriDon.setText(_translate("MainWindow", "GERİ DÖN"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
