# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sikcasorulansorular.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 592)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonSSSGeriDon = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonSSSGeriDon.setGeometry(QtCore.QRect(680, 500, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButtonSSSGeriDon.setFont(font)
        self.pushButtonSSSGeriDon.setStyleSheet("background-color: rgb(255, 237, 224);\n"
"background-color: rgb(214, 214, 214);\n"
"font: 10pt \"Arial\";\n"
"border-radius:7px;")
        self.pushButtonSSSGeriDon.setObjectName("pushButtonSSSGeriDon")
        self.textEditSSS = QtWidgets.QTextEdit(self.centralwidget)
        self.textEditSSS.setGeometry(QtCore.QRect(70, 20, 561, 511))
        self.textEditSSS.setStyleSheet("background-color: rgb(95, 95, 95);")
        self.textEditSSS.setReadOnly(True)
        self.textEditSSS.setObjectName("textEditSSS")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SIKCA SORULAN SORULAR-EMR OTO"))
        self.pushButtonSSSGeriDon.setText(_translate("MainWindow", "GERİ DÖN"))
        self.textEditSSS.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">1- Araç bakımı ne sıklıkla yapılmalıdır?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Genellikle araç bakımı, aracın yaşına, kilometresine ve kullanım koşullarına bağlı olarak değişir. Ancak genel bir kılavuz olarak, araç bakımı her 6 ayda bir veya 10.000 ila 15.000 kilometrede bir yapılmalıdır.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">2- Lastik basıncını nasıl kontrol ederim ve ne sıklıkla kontrol etmeliyim?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Lastik basıncını bir basınç göstergesi kullanarak kontrol edebilirsiniz. Genellikle lastik basıncı, araç üreticisinin belirttiği değerlere uygun olmalıdır. Lastik basıncını her ay düzenli olarak kontrol etmek iyi bir uygulamadır.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">3- Yağ değişimi ne zaman yapılmalıdır?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Yağ değişimi aracın yağ tipine ve kullanım koşullarına bağlı olarak değişir, ancak genellikle her 5.000 ila 10.000 kilometrede bir yapılmalıdır. Araç üreticisinin tavsiyelerine uygun olarak yağ değişimi yapılmalıdır.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">4- Fren balatalarının değişme zamanı nasıl belirlenir?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Fren balatalarının değişme zamanı, fren pedalının hissiyatında veya aracın frenleme performansında herhangi bir değişiklik fark edildiğinde veya fren balatalarının kalınlığı belirli bir ölçüme ulaştığında belirlenir. Genellikle fren balataları 20.000 ila 60.000 kilometre arasında dayanabilir, ancak sürüş koşullarıyla değişir.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">5- Araçta gözlemlenen belirli semptomlar neler olabilir ve bunlar hangi sorunları işaret edebilir?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Araçta gözlemlenen belirli semptomlar, örneğin motorun anormal sesleri, titreşimler, uyarı ışıklarının yanması gibi durumlar, genellikle bir sorun olduğunu işaret eder. Bu semptomlar, motor, şanzıman, fren sistemi, süspansiyon ve diğer bileşenlerle ilgili olabilir ve bir uzman tarafından incelenmelidir.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">6- Araç garanti kapsamında hangi hizmetler sunulmaktadır?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Araç garanti kapsamı üreticiye ve araç modeline bağlı olarak değişir. Genellikle garanti, belirli bir süre veya belirli bir kilometre sınırlaması içinde motor, şanzıman ve diğer belirli bileşenler için geçerlidir. Garanti kapsamındaki hizmetler, yetkili servis merkezlerinde sunulur.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#ffffff;\">7- Yakıt verimliliğini artırmak için neler yapılabilir?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Yakıt verimliliğini artırmak için araç düzenli olarak bakılmalı, lastik basıncı kontrol edilmeli, hız sınırlarına uyulmalı, ani hızlanmalardan kaçınılmalı ve gereksiz yükler araçtan çıkarılmalıdır. Ayrıca, düzenli olarak motor yağı ve filtreleri değiştirmek de önemlidir.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">8- Soğutma sistemi nasıl kontrol edilir ve bakımı nasıl yapılır?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Soğutma sistemi, radyatördeki antifriz seviyesinin kontrol edilmesini ve gerektiğinde antifriz eklenmesini gerektirir. Ayrıca, soğutma sistemindeki hortumların ve bağlantı noktalarının sızıntı veya hasar açısından kontrol edilmesi önemlidir. Soğutma sistemi bakımı, araç üreticisinin belirttiği periyotlarda yapılmalıdır.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">9- Aracın elektrik sistemi ve bataryasıyla ilgili bakım gereksinimleri nelerdir?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Aracın elektrik sistemi ve bataryası, araç çalıştırılmadan önce akünün temizliğinin yapılmasını ve terminallerin oksitlenmesini önlemek için terminallerin sık sık kontrol edilmesini gerektirir. Ayrıca, araç içindeki elektriksel ekipmanların düzgün çalışmasını sağlamak için sigorta kutusunun ve elektrik bağlantılarının kontrol edilmesi önemlidir.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; color:#ffffff;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600; color:#ffffff;\">10- Kış mevsiminde araç bakımı ve hazırlığı konusunda öneriler nelerdir?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" color:#ffffff;\">Kış mevsiminde araç bakımı ve hazırlığı için lastiklerin kış lastikleriyle değiştirilmesi, antifriz seviyesinin kontrol edilmesi, cam suyunun antifriz eklenmesi, sileceklerin kontrol edilmesi, aracın kışlık acil durum kitiyle donatılması ve aracın genel bir kontrolünün yapılması önerilir.</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
